### ISSUE TITLE
ValueError: RegionType NaN

### ISSUE THREAD

**Issue by KanduriC** [uio-bmi/immuneML#100]
Hi @pavlovicmilena! I am using the attached YAML [specification file](https://github.com/uio-bmi/immuneML/files/7000721/repertoire_implanting_rate__2e-05_-_ml_instruction.yaml.txt) and I get a valueerror in RegionType checking.  
The [stderr](https://github.com/uio-bmi/immuneML/files/7000733/varying_rep_rate_run_1_ml_stderr.txt) is attached. Could you help me figure out the error!? Thanks ..

**Comment by pavlovicmilena** [comment]
Hi :) I cannot replicate this locally, does this error also occur when you use a randomly generated dataset? For instance, if you define a dataset like this:

```
    dataset1:
      format: RandomRepertoireDataset
      params:
        repertoire_count: 50
        sequence_count_probabilities:
          10: 1.
        sequence_length_probabilities:
          5: 1.
        labels:
          cancer:
            True: 0.5
            False: 0.5
```

Alternatively, could you maybe share the dataset files? 

My guess is that the problem might be a mismatch between versions (dataset imported with one version but used with the newer one), but have to check either with your dataset files or in your setup with a new dataset :)
